-- Auto-generated by Raidstrats.gg admin (spell-card Lua export).
-- Generated: 2026-06-25T18:40:55.525Z
-- Strat ID: 32
-- Raid: Sporefall
-- Boss: Rotmire

local addonName = ...
local AceAddon = LibStub("AceAddon-3.0")
local Addon =
    AceAddon:GetAddon(addonName, true) or
    AceAddon:GetAddon("Raidstratsgg", true) or
    AceAddon:GetAddon("raidstratsgg", true)
if not Addon then return end

Addon.BossOverviewData = Addon.BossOverviewData or {}
Addon.BossOverviewData.byName = Addon.BossOverviewData.byName or {}

Addon.BossOverviewData.byName["rotmire"] = {
    roles = {
        tank = [[Quick breakdown (Tank)

- |Hspell:1221622|h[Add Spawn]|h|r
  Now spawns a mix of Shroomlings and Funglings.

- |Hspell:1222684|h[Spread Adds]|h|r
  If a Shroomling and a Fungling dies within 10 yards of each other, a [spell=1222495] will spawn.
  Key tips: <p><br></p>

- |Hspell:1222495|h[Doom Shroom]|h|r
  Raid wipe from [spell=1222684].

- |Hspell:1221622|h[Add Spawn]|h|r - Spawns adds
  Spawns Shroomlings, Funglings and a Sporecap
  Key tips: <ul><li>Spawns 3 Shroomlings, 3 Funglings and 1 Sporecap in 20man.</li><li>Fixates random players</li><li>Shroomlings and Funglings fixate on players - make sure they die apart</li><li>Ranged should focus far Sporecap on 2nd set</li></ul><p><br></p>

- |Hspell:1221714|h[Sporecap cast]|h|r - Interrupt
  Interruptable cast from Sporecap - 1 Spawns every [spell=1221622].
  Key tips: <ul><li>Casts roughly every 8 seconds</li><li>Assign ranged kicks on the far Sporecap</li></ul><p><br></p>

- |Hspell:1221637|h[Shroom Spawn]|h|r - Spawns adds
  Spawns Bursting Shrooms to kill
  Key tips: <p><ul><li>Happens roughly every 2 minutes</li></ul></p>

- |Hspell:1221787|h[AoE Damage]|h|r - Heal Through
  Main healer mechanic - applies permanent rot damage stacks to the boss
  Key tips: <ul><li>Applies 4 stacks to the  boss, permanently increasing the rot damage taken<br></li></ul>

- |Hspell:1222176|h[Rot Stacks]|h|r - Heal Through
  Permanent stacking rot damage
  Key tips: <p><ul><li>4 stacks are aplied every&nbsp;[spell=1221787] cast.</li><li>Triage-heal, prioritizing low health targets or targets with&nbsp;[spell=1222088]</li></ul></p>

- |Hspell:1221781|h[Tank Buster]|h|r - Taunt Swap
  Physical damage tank hit
  Key tips: <ul><li>Happens roughly every 12 seconds</li><li>Applies a 14 second debuff</li><li>Swap after every cast</li></ul><p><br></p>]],
        healer = [[Quick breakdown (Healer)

- |Hspell:1221622|h[Add Spawn]|h|r
  Now spawns a mix of Shroomlings and Funglings.

- |Hspell:1222684|h[Spread Adds]|h|r
  If a Shroomling and a Fungling dies within 10 yards of each other, a [spell=1222495] will spawn.
  Key tips: <p><br></p>

- |Hspell:1222495|h[Doom Shroom]|h|r
  Raid wipe from [spell=1222684].

- |Hspell:1221622|h[Add Spawn]|h|r - Spawns adds
  Spawns Shroomlings, Funglings and a Sporecap
  Key tips: <ul><li>Spawns 3 Shroomlings, 3 Funglings and 1 Sporecap in 20man.</li><li>Fixates random players</li><li>Shroomlings and Funglings fixate on players - make sure they die apart</li><li>Ranged should focus far Sporecap on 2nd set</li></ul><p><br></p>

- |Hspell:1221714|h[Sporecap cast]|h|r - Interrupt
  Interruptable cast from Sporecap - 1 Spawns every [spell=1221622].
  Key tips: <ul><li>Casts roughly every 8 seconds</li><li>Assign ranged kicks on the far Sporecap</li></ul><p><br></p>

- |Hspell:1221637|h[Shroom Spawn]|h|r - Spawns adds
  Spawns Bursting Shrooms to kill
  Key tips: <p><ul><li>Happens roughly every 2 minutes</li></ul></p>

- |Hspell:1222088|h[Slow Debuff]|h|r - Move
  Debuff - Drops permanent puddles at the edges of the room
  Key tips: <p><ul><li>Happens twice to every cycle</li><li>Applies to 3 players</li></ul></p>

- |Hspell:1221787|h[AoE Damage]|h|r - Heal Through
  Main healer mechanic - applies permanent rot damage stacks to the boss
  Key tips: <ul><li>Applies 4 stacks to the  boss, permanently increasing the rot damage taken<br></li></ul>

- |Hspell:1222176|h[Rot Stacks]|h|r - Heal Through
  Permanent stacking rot damage
  Key tips: <p><ul><li>4 stacks are aplied every&nbsp;[spell=1221787] cast.</li><li>Triage-heal, prioritizing low health targets or targets with&nbsp;[spell=1222088]</li></ul></p>]],
        dps = [[Quick breakdown (DPS)

- |Hspell:1221622|h[Add Spawn]|h|r
  Now spawns a mix of Shroomlings and Funglings.

- |Hspell:1222684|h[Spread Adds]|h|r
  If a Shroomling and a Fungling dies within 10 yards of each other, a [spell=1222495] will spawn.
  Key tips: <p><br></p>

- |Hspell:1222495|h[Doom Shroom]|h|r
  Raid wipe from [spell=1222684].

- |Hspell:1221622|h[Add Spawn]|h|r - Spawns adds
  Spawns Shroomlings, Funglings and a Sporecap
  Key tips: <ul><li>Spawns 3 Shroomlings, 3 Funglings and 1 Sporecap in 20man.</li><li>Fixates random players</li><li>Shroomlings and Funglings fixate on players - make sure they die apart</li><li>Ranged should focus far Sporecap on 2nd set</li></ul><p><br></p>

- |Hspell:1221714|h[Sporecap cast]|h|r - Interrupt
  Interruptable cast from Sporecap - 1 Spawns every [spell=1221622].
  Key tips: <ul><li>Casts roughly every 8 seconds</li><li>Assign ranged kicks on the far Sporecap</li></ul><p><br></p>

- |Hspell:1221637|h[Shroom Spawn]|h|r - Spawns adds
  Spawns Bursting Shrooms to kill
  Key tips: <p><ul><li>Happens roughly every 2 minutes</li></ul></p>

- |Hspell:1222088|h[Slow Debuff]|h|r - Move
  Debuff - Drops permanent puddles at the edges of the room
  Key tips: <p><ul><li>Happens twice to every cycle</li><li>Applies to 3 players</li></ul></p>

- |Hspell:1221787|h[AoE Damage]|h|r - Heal Through
  Main healer mechanic - applies permanent rot damage stacks to the boss
  Key tips: <ul><li>Applies 4 stacks to the  boss, permanently increasing the rot damage taken<br></li></ul>

- |Hspell:1222176|h[Rot Stacks]|h|r - Heal Through
  Permanent stacking rot damage
  Key tips: <p><ul><li>4 stacks are aplied every&nbsp;[spell=1221787] cast.</li><li>Triage-heal, prioritizing low health targets or targets with&nbsp;[spell=1222088]</li></ul></p>]],
    },
    spell_cards = {
        {
          name = [[Add Spawn]],
          spell_id = 1221622,
          action = [[]],
          role = [[Changed]],
          utility_flag = [[]],
          phase_name = [[Quick Overview]],
          phase_type = [[quick_overview]],
          note = [[Now spawns a mix of Shroomlings and Funglings.]],
          key_tips = [[]],
          raidlead_notes = [[]],
          spell_tip_roles = {}
        },
        {
          name = [[Spread Adds]],
          spell_id = 1222684,
          action = [[]],
          role = [[New]],
          utility_flag = [[]],
          phase_name = [[Quick Overview]],
          phase_type = [[quick_overview]],
          note = [[If a Shroomling and a Fungling dies within 10 yards of each other, a [spell=1222495] will spawn.]],
          key_tips = [[<p><br></p>]],
          raidlead_notes = [[]],
          spell_tip_roles = {}
        },
        {
          name = [[Doom Shroom]],
          spell_id = 1222495,
          action = [[]],
          role = [[New]],
          utility_flag = [[]],
          phase_name = [[Quick Overview]],
          phase_type = [[quick_overview]],
          note = [[Raid wipe from [spell=1222684].]],
          key_tips = [[]],
          raidlead_notes = [[]],
          spell_tip_roles = {}
        },
        {
          name = [[Add Spawn]],
          spell_id = 1221622,
          action = [[Spawns adds]],
          role = [[Boss]],
          utility_flag = [[]],
          phase_name = [[Encounter]],
          phase_type = [[phase]],
          note = [[Spawns Shroomlings, Funglings and a Sporecap]],
          key_tips = [[<ul><li>Spawns 3 Shroomlings, 3 Funglings and 1 Sporecap in 20man.</li><li>Fixates random players</li><li>Shroomlings and Funglings fixate on players - make sure they die apart</li><li>Ranged should focus far Sporecap on 2nd set</li></ul><p><br></p>]],
          raidlead_notes = [[]],
          spell_tip_roles = {"tank", "healer", "rdps", "mdps"}
        },
        {
          name = [[Sporecap cast]],
          spell_id = 1221714,
          action = [[Interrupt]],
          role = [[]],
          utility_flag = [[interrupt]],
          phase_name = [[Encounter]],
          phase_type = [[phase]],
          note = [[Interruptable cast from Sporecap - 1 Spawns every [spell=1221622].]],
          key_tips = [[<ul><li>Casts roughly every 8 seconds</li><li>Assign ranged kicks on the far Sporecap</li></ul><p><br></p>]],
          raidlead_notes = [[]],
          spell_tip_roles = {"tank", "healer", "rdps", "mdps"}
        },
        {
          name = [[Shroom Spawn]],
          spell_id = 1221637,
          action = [[Spawns adds]],
          role = [[Boss]],
          utility_flag = [[]],
          phase_name = [[Encounter]],
          phase_type = [[phase]],
          note = [[Spawns Bursting Shrooms to kill]],
          key_tips = [[<p><ul><li>Happens roughly every 2 minutes</li></ul></p>]],
          raidlead_notes = [[]],
          spell_tip_roles = {"tank", "healer", "rdps", "mdps"}
        },
        {
          name = [[Slow Debuff]],
          spell_id = 1222088,
          action = [[Move]],
          role = [[Random player]],
          utility_flag = [[speed_utility]],
          phase_name = [[Encounter]],
          phase_type = [[phase]],
          note = [[Debuff - Drops permanent puddles at the edges of the room]],
          key_tips = [[<p><ul><li>Happens twice to every cycle</li><li>Applies to 3 players</li></ul></p>]],
          raidlead_notes = [[]],
          spell_tip_roles = {"healer", "rdps", "mdps"}
        },
        {
          name = [[AoE Damage]],
          spell_id = 1221787,
          action = [[Heal Through]],
          role = [[]],
          utility_flag = [[]],
          phase_name = [[Encounter]],
          phase_type = [[phase]],
          note = [[Main healer mechanic - applies permanent rot damage stacks to the boss]],
          key_tips = [[<ul><li>Applies 4 stacks to the  boss, permanently increasing the rot damage taken<br></li></ul>]],
          raidlead_notes = [[<p>Make sure you backload your healer cooldowns, as the ending of the fight is going to be harder than the beginning.<br></p>]],
          spell_tip_roles = {"tank", "healer", "rdps", "mdps"}
        },
        {
          name = [[Rot Stacks]],
          spell_id = 1222176,
          action = [[Heal Through]],
          role = [[Healers]],
          utility_flag = [[]],
          phase_name = [[Encounter]],
          phase_type = [[phase]],
          note = [[Permanent stacking rot damage]],
          key_tips = [[<p><ul><li>4 stacks are aplied every&nbsp;[spell=1221787] cast.</li><li>Triage-heal, prioritizing low health targets or targets with&nbsp;[spell=1222088]</li></ul></p>]],
          raidlead_notes = [[]],
          spell_tip_roles = {"tank", "healer", "rdps", "mdps"}
        },
        {
          name = [[Tank Buster]],
          spell_id = 1221781,
          action = [[Taunt Swap]],
          role = [[Tanks]],
          utility_flag = [[personal_defensive]],
          phase_name = [[Encounter]],
          phase_type = [[phase]],
          note = [[Physical damage tank hit]],
          key_tips = [[<ul><li>Happens roughly every 12 seconds</li><li>Applies a 14 second debuff</li><li>Swap after every cast</li></ul><p><br></p>]],
          raidlead_notes = [[]],
          spell_tip_roles = {"tank"}
        }
    }
}